# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ced_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subactivity_objectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Entered', models.DateTimeField()),
                ('User', models.CharField(max_length=50)),
                ('Objective', models.ManyToManyField(db_column=b'Objective', to='ced_main.subactivity_objectives_data')),
            ],
        ),
        migrations.AlterField(
            model_name='batchupload',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 6, 23, 346000)),
        ),
        migrations.AlterField(
            model_name='batchupload_groups',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 6, 23, 346000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 6, 23, 346000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Last_Updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 6, 23, 346000)),
        ),
        migrations.AddField(
            model_name='subactivity_objectives',
            name='Project_ID',
            field=models.ForeignKey(db_column=b'Project_ID', on_delete=django.db.models.deletion.PROTECT, to='ced_main.project_info'),
        ),
    ]
