# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ced_main', '0003_auto_20180927_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subactivity_effectiveness_statement',
            old_name='Objective',
            new_name='Effectiveness_Statement',
        ),
        migrations.RenameField(
            model_name='subactivity_methods',
            old_name='Objective',
            new_name='Method',
        ),
        migrations.AlterField(
            model_name='batchupload',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 12, 50, 254000)),
        ),
        migrations.AlterField(
            model_name='batchupload_groups',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 12, 50, 254000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 12, 50, 254000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Last_Updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 12, 50, 254000)),
        ),
    ]
