# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 19:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ced_main', '0004_auto_20180927_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subactivity_effectiveness_statement',
            new_name='subactivity_effective_state',
        ),
        migrations.RenameModel(
            old_name='subactivity_effectiveness_statement_data',
            new_name='subactivity_effective_state_data',
        ),
        migrations.AlterField(
            model_name='batchupload',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 14, 33, 438000)),
        ),
        migrations.AlterField(
            model_name='batchupload_groups',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 14, 33, 438000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 14, 33, 438000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Last_Updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 13, 14, 33, 438000)),
        ),
    ]
