# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ced_main', '0006_auto_20180928_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactivity_methods_data',
            name='Ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchupload',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 13, 21, 16, 300000)),
        ),
        migrations.AlterField(
            model_name='batchupload_groups',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 13, 21, 16, 300000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 13, 21, 16, 300000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Last_Updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 13, 21, 16, 300000)),
        ),
    ]
