# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-28 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ced_main', '0007_auto_20180928_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchupload',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 13, 21, 49, 474000)),
        ),
        migrations.AlterField(
            model_name='batchupload_groups',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 13, 21, 49, 474000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 13, 21, 49, 474000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Last_Updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 13, 21, 49, 474000)),
        ),
    ]
