# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ced_main', '0008_auto_20180928_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactivity_effective_state_data',
            name='Ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchupload',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 14, 33, 14, 649000)),
        ),
        migrations.AlterField(
            model_name='batchupload_groups',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 14, 33, 14, 649000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 14, 33, 14, 649000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Last_Updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 14, 33, 14, 649000)),
        ),
    ]
