# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-01 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ced_main', '0009_auto_20181001_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='subactivity_objectives_data',
            name='Ordering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batchupload',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 15, 4, 45, 926000)),
        ),
        migrations.AlterField(
            model_name='batchupload_groups',
            name='Upload_Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 15, 4, 45, 926000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Date_Created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 15, 4, 45, 926000)),
        ),
        migrations.AlterField(
            model_name='project_info',
            name='Last_Updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 15, 4, 45, 926000)),
        ),
    ]
