update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Livestock & Rangeland Management' and subactivity ='---Select a Subactivity---';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Reclamation Efforts' and subactivity ='Oil and gas reclamation with goal of sage brush restoration';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Population Augmentation' and subactivity ='Translocation';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Fence Marking';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Habitat Protection: Habitat Acquisition' and subactivity ='Habitat Protected by Acquisition for Long-Term Conservation';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Restoration' and subactivity ='Habitat Restoration';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Regulatory Mechanisms, Plans, Policy' and subactivity ='Other Regulatory Mechanisms, Plans, Policies';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Powerline Retrofitting / Modification: Transmission Line';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Structure Removed: Other (see notes)';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Restoration' and subactivity ='Habitat Restoration Following Wildfire Disturbance';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Structure Removed: Wind Turbines';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Powerline Retrofitting / Modification: Distribution Line';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Conifer Removal' and subactivity ='Conifer Removal: Mixed Phase 1 and 2';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Livestock & Rangeland Management' and subactivity ='Improved grazing practices in place (rest rotation, riparian areas fenced off)';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Conifer Removal' and subactivity ='Conifer Removal: Phase 1';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Conifer Removal' and subactivity ='Conifer Removal: Phase 2';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Wildfire Pre-suppression Efforts' and subactivity ='Fuel Reduction Treatments';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Fence Removal';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Reclamation Efforts' and subactivity ='Mine reclamation with goal of sage brush restoration';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Habitat Protection: Conservation Easement' and subactivity ='Habitat Protected by Easement for Long-Term Conservation';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Structure Removed: Road';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Non-regulatory Conservation Strategies' and subactivity ='Voluntary State Restoration Program';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Wildfire: Interagency Pre-suppression Planning Efforts' and subactivity ='Mutual Aid & Cross Jurisdictional Agreements';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Regulatory Mechanisms, Plans, Policy' and subactivity ='State Conservation Plan';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Wildfire Pre-suppression Efforts' and subactivity ='Fuel Breaks ';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Non-regulatory Conservation Strategies' and subactivity ='Voluntary Local Government Restoration Program';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Fence Modification';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Non-regulatory Conservation Strategies' and subactivity ='Programmatic Candidate Conservation Agreement with Assurances';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Non-regulatory Conservation Strategies' and subactivity ='Voluntary NGO Restoration Program';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Conifer Removal' and subactivity ='Conifer Removal: Phase 3';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Non-regulatory Conservation Strategies' and subactivity ='Programmatic Reclamation Plan';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Non-regulatory Conservation Strategies' and subactivity ='Programmatic Candidate Conservation Agreement';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Regulatory Mechanisms, Plans, Policy' and subactivity ='Local Government Plan';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Non-regulatory Conservation Strategies' and subactivity ='Voluntary Federal Restoration Program';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Powerline Burial: Distribution Line';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Infrastructure Removal and Modification' and subactivity ='Structure Removed: Powerline';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Recreation Management' and subactivity ='Road and Trail closure';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Non-regulatory Conservation Strategies' and subactivity ='Programmatic Restoration Plan (Non-Wildfire related)';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Restoration' and subactivity ='BLM Federal Land Use Plan';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Wild Equid Management' and subactivity ='Wild Equid Gather';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Restoration' and subactivity ='Programmatic Restoration Plan (Wildfire)';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Wildfire: Interagency Pre-suppression Planning Efforts' and subactivity ='Wildfire Related Conservation Strategy (Pre-suppression Plans)';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Reclamation Efforts' and subactivity ='Habitat Restoration Following Wildfire Disturbance';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Restoration' and subactivity ='Fuel Reduction Treatments';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Restoration' and subactivity ='Conifer Removal: Mixed Phase 1 and 2';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Reclamation Efforts' and subactivity ='Habitat Restoration';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration:  Livestock & Rangeland Management' and subactivity ='Habitat Restoration';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='Restoration: Habitat Reclamation Efforts' and subactivity ='---Select a Subactivity---';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='NON-REGULATORY CONSERVATION PLANS (Strategies, BMPs)' and subactivity ='Non-regulatory Conservation Strategies';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='REGULATORY MECHANISMS: Plans, Policies' and subactivity ='State Conservation Plan';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='RESTORATION: Conifer Removal' and subactivity ='Conifer Removal (all phases)';
update ced_main_project_info set typeact = 'Non-Spatial Project' where activity='SAGEBRUSH PROTECTION' and subactivity ='Conservation Easement';
